fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: requirements-txt-fixer
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii, --no-sort-keys]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    require_serial: true
    args: [--autofix, --indent, '2']

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
    require_serial: true
    types: [python]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
  - id: ruff
    args: [--fix]

- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: poetry run pyright
    verbose: true
    language: system
    pass_filenames: false

- repo: local
  hooks:
  - id: deptry
    name: deptry
    entry: poetry run deptry .
    verbose: true
    language: system
    pass_filenames: false
