version: "3.9"

services:
  web:
    volumes:
      - "${project_dir}:/usr/src/app"
    environment:
      - "redis_host=${redis_host}"
      - "redis_port=${redis_port}"
      - "mongo_host=${mongo_host}"
      - "mongo_port=${mongo_port}"
      - "mongo_dbname=${mongo_dbname}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
      - "NemoBotToken=${NemoBotToken}"
      - "tg_my_id=${tg_my_id}"
      - "notificator_port=${notificator_port}"
      - "callbackUrl=${callbackUrl}"
      - "hubUrl=${hubUrl}"
    ports:
      - "${notificator_port}:${notificator_port}"
    build: .
    restart: always
    depends_on:
      - redis
      - mongo
  mongo:
    image: mongo:4-focal
    volumes:
      - "${mongo_volume_path}:/data/db:rw"
      - "${mongo_initdb_path}:/docker-entrypoint-initdb.d:ro"
    environment:
      - "MONGO_INITDB_DATABASE=${mongo_dbname}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "${mongo_port}:27017"

  redis:
    image: redis:6
    volumes:
      - "${redis_volume_path}:/data"
    ports:
      - "${redis_port}:6379"

