MISSING_MESSAGE_OR_TEXT: str = "Missing message or text"
MISSING_MESSAGE_OR_CHAT: str = "Missing message or chat"
MISSING_MESSAGE_OR_CHAT_OR_TEXT: str = "Missing message or chat or text"
MISSING_MESSAGE_OR_FROM_USER: str = "Missing message or from_user"
MISSING_CALLBACK_QUERY: str = "Missing callback_query"
MISSING_CALLBACK_QUERY_OR_DATA: str = "Missing callback_query or data"
MISSING_CALLBACK_QUERY_OR_FROM_USER: str = "Missing callback_query or from_user"
MONGO_CONNECTION_FAILURE: str = "Mongo ConnectionFailure"
